version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: ragent-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragent
    volumes:
      - pgdata:/var/lib/postgresql
      - ./resources/database/schema_pg.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./resources/database/init_data_pg.sql:/docker-entrypoint-initdb.d/02-init-data.sql

  redis:
    image: redis:7
    container_name: ragent-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    container_name: ragent-rocketmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"

  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    container_name: ragent-rocketmq-broker
    ports:
      - "10911:10911"
      - "10909:10909"
    depends_on:
      - rocketmq-namesrv
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /opt/rocketmq/broker.conf
    volumes:
      - ./broker.conf:/opt/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"

  minio:
    image: minio/minio
    container_name: ragent-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rustfsadmin
      MINIO_ROOT_PASSWORD: rustfsadmin
    command: server /data --console-address ":9001"

volumes:
  pgdata:
